### ISSUE TITLE
Question about synchronization between training steps and data collection

### ISSUE THREAD

**Issue by AndreasXie** [Shengjiewang-Jason/EfficientZeroV2#12]
Hi! I’m curious about how learning steps and data collection from the environment are coordinated. From my understanding, the learner updates the agent's weights using the replay buffer and isn’t directly involved in data collection—is that correct? It also seems like the learner is controlled by the total training steps in the configuration (e.g., 120k for Atari100K).

Could you clarify how the balance between training and data collection is maintained? Without synchronization, it seems possible to hit the total training steps (e.g., 120k) before completing, say, 50k environment steps. Is there a mechanism in the code to regulate this? Any clarification would be greatly appreciated!

**Comment by Shengjiewang-Jason** [comment]
Thank you a lot for the question. For the first question, your understanding is right. Additionally, the balance between training and data collection is important. Also, we often adjust the numbers of ``data_worker`` and ``batch_worker`` in the config file to avoid the situation you mentioned.  Basically, more data workers can improve the efficiency of data collection.

**Comment by AndreasXie** [comment]
So, the balance between training and data collection is only controlled by the ratio of data workers to batch workers? 

For example, if one config setting has an issue that total training steps are reached before collecting 50k data, we should manually change the number of data worker to 2 or 3 times of it to have a more efficient data collecting.

**Comment by Shengjiewang-Jason** [comment]
Yeah, you are right. We didn't meet this problem in the Atari and DMC benchmarks, and the training is usually slower than data collection. If you test it in the environment you created, I think you should increase the number of data workers.

**Comment by AndreasXie** [comment]
Thanks for your reply!
