### ISSUE TITLE
Can't train

### ISSUE THREAD

**Issue by tapicl** [Shengjiewang-Jason/EfficientZeroV2#3]
I followed the installation instructions.

```
python --version
Python 3.8.10
```

```
pip show torchrl
Name: torchrl
Version: 0.1.0
Summary: UNKNOWN
Home-page: https://github.com/pytorch/rl
Author: torchrl contributors
Author-email: [vmoens@fb.com](mailto:vmoens@fb.com)
License: BSD
Location: /ez2/lib/python3.8/site-packages
Requires: tensordict, packaging, torch, numpy, cloudpickle
```

```
pip show torch
Name: torch
Version: 2.0.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: [packages@pytorch.org](mailto:packages@pytorch.org)
License: BSD-3
Location: /ez2/lib/python3.8/site-packages
Requires: nvidia-cuda-runtime-cu11, sympy, nvidia-cudnn-cu11, jinja2, nvidia-cusparse-cu11, nvidia-nccl-cu11, nvidia-nvtx-cu11, nvidia-cufft-cu11, nvidia-cuda-cupti-cu11, triton, nvidia-curand-cu11, nvidia-cublas-cu11, networkx, nvidia-cuda-nvrtc-cu11, nvidia-cusolver-cu11, filelock, typing-extensions
Required-by: triton, torchvision, torchrl, torchaudio, tensordict, kornia
```

```
python ez/train.py exp_config=ez/config/exp/atari.yaml
Traceback (most recent call last):
...
    import torchrl
  File "/ez2/lib/python3.8/site-packages/torchrl/__init__.py", line 32, in <module>
    import torchrl.collectors
  File "/ez2/lib/python3.8/site-packages/torchrl/collectors/__init__.py", line 6, in <module>
    from .collectors import (
  File "/ez2/lib/python3.8/site-packages/torchrl/collectors/collectors.py", line 33, in <module>
    from torchrl.data.tensor_specs import TensorSpec
  File "/ez2/lib/python3.8/site-packages/torchrl/data/__init__.py", line 7, in <module>
    from .replay_buffers import (
  File "/ez2/lib/python3.8/site-packages/torchrl/data/replay_buffers/__init__.py", line 6, in <module>
    from .replay_buffers import (
  File "/ez2/lib/python3.8/site-packages/torchrl/data/replay_buffers/replay_buffers.py", line 20, in <module>
    from .samplers import PrioritizedSampler, RandomSampler, Sampler
  File "/ez2/lib/python3.8/site-packages/torchrl/data/replay_buffers/samplers.py", line 20, in <module>
    from .storages import Storage
  File "/ez2/lib/python3.8/site-packages/torchrl/data/replay_buffers/storages.py", line 14, in <module>
    from tensordict.memmap import MemmapTensor
ImportError: cannot import name 'MemmapTensor' from 'tensordict.memmap' (/ez2/lib/python3.8/site-packages/tensordict/memmap.py)
```

**Comment by Shengjiewang-Jason** [comment]
Thanks for providing the new installation bug.  Unfortunately, we didn't meet the problem before. But we can provide our version of tensordict package. Then you can make sure the following commands work on your end.
![截屏2024-08-13 23 04 23](https://github.com/user-attachments/assets/4d1aedc5-7301-47a1-ba23-2052fc977672)

**Comment by tapicl** [comment]
Could you please paste the result of pip list in your environment here please?

**Comment by Shengjiewang-Jason** [comment]
Package                    Version      Editable project location
-------------------------- ------------ ------------------------------------
absl-py                    2.0.0
aiohttp                    3.9.1
aiohttp-cors               0.7.0
aioredis                   2.0.1
aiosignal                  1.3.1
ale-py                     0.7.5
antlr4-python3-runtime     4.9.3
appdirs                    1.4.4
asttokens                  2.4.1
async-timeout              4.0.3
attrs                      23.1.0
AutoROM                    0.4.2
AutoROM.accept-rom-license 0.6.1
av                         11.0.0
backcall                   0.2.0
beautifulsoup4             4.12.2
blessed                    1.20.0
blinker                    1.8.2
brax                       0.9.4
cached-property            1.5.2
cachetools                 5.3.2
certifi                    2023.11.17
charset-normalizer         3.3.2
chex                       0.1.7
click                      8.1.7
cloudpickle                3.0.0
cmake                      3.27.7
colorama                   0.4.6
colorednoise               2.2.0
colorful                   0.5.5
comm                       0.1.4
contextlib2                21.6.0
contourpy                  1.1.1
cycler                     0.12.1
Cython                     3.0.5
debugpy                    1.6.7
decorator                  5.1.1
dm-control                 1.0.15
dm-env                     1.6
dm-tree                    0.1.8
dmc2gym                    1.0.0        /home/wangshengjie/RL/dmc2gym
docker-pycreds             0.4.0
entrypoints                0.4
etils                      1.3.0
executing                  2.0.1
Farama-Notifications       0.0.4
filelock                   3.13.1
Flask                      3.0.3
Flask-Cors                 4.0.1
flax                       0.7.2
fonttools                  4.47.0
frozenlist                 1.4.0
gitdb                      4.0.11
GitPython                  3.1.40
glfw                       2.6.2
google                     3.0.0
google-api-core            2.14.0
google-auth                2.23.4
google-auth-oauthlib       1.0.0
googleapis-common-protos   1.61.0
gpustat                    1.1.1
grpcio                     1.59.2
gym                        0.22.0
gym-notices                0.0.8
gymnasium                  0.29.1
gymnax                     0.0.6
humanoid-bench             0.1          /home/wangshengjie/RL/humanoid-bench
hydra-core                 1.3.2
idna                       3.6
imageio                    2.31.5
imageio-ffmpeg             0.4.9
importlib-metadata         6.8.0
importlib-resources        6.1.1
ipdb                       0.13.13
ipykernel                  6.28.0
ipython                    8.12.0
itsdangerous               2.2.0
jax                        0.4.13
jaxlib                     0.4.13
jaxopt                     0.8.3
jedi                       0.19.1
Jinja2                     3.1.2
jsonschema                 4.19.2
jsonschema-specifications  2023.7.1
jupyter-client             7.3.4
jupyter_core               5.6.0
kiwisolver                 1.4.5
kornia                     0.7.0
labmaze                    1.0.6
line-profiler              4.1.2
lit                        17.0.6
lxml                       4.9.3
Markdown                   3.5.1
markdown-it-py             3.0.0
MarkupSafe                 2.1.3
matplotlib                 3.7.4
matplotlib-inline          0.1.6
mdurl                      0.1.2
ml-collections             0.1.1
ml-dtypes                  0.2.0
mpmath                     1.3.0
msgpack                    1.0.7
mujoco                     3.1.6
mujoco-mjx                 3.1.6
multidict                  6.0.4
nest-asyncio               1.5.8
networkx                   3.1
numpy                      1.23.5
nvidia-cublas-cu11         11.10.3.66
nvidia-cuda-cupti-cu11     11.7.101
nvidia-cuda-nvrtc-cu11     11.7.99
nvidia-cuda-runtime-cu11   11.7.99
nvidia-cudnn-cu11          8.5.0.96
nvidia-cufft-cu11          10.9.0.58
nvidia-curand-cu11         10.2.10.91
nvidia-cusolver-cu11       11.4.0.1
nvidia-cusparse-cu11       11.7.4.91
nvidia-ml-py               12.535.133
nvidia-nccl-cu11           2.14.3
nvidia-nvtx-cu11           11.7.91
oauthlib                   3.2.2
omegaconf                  2.3.0
opencensus                 0.11.3
opencensus-context         0.1.3
opencv-python              4.8.1.78
opt-einsum                 3.3.0
optax                      0.1.8
orbax-checkpoint           0.2.3
packaging                  23.2
pandas                     2.0.3
parso                      0.8.3
pathtools                  0.1.2
pexpect                    4.8.0
pickleshare                0.7.5
Pillow                     10.1.0
pip                        23.3.1
pkgutil_resolve_name       1.3.10
platformdirs               4.1.0
prometheus-client          0.18.0
prompt-toolkit             3.0.41
protobuf                   3.20.1
psutil                     5.9.0
ptyprocess                 0.7.0
pure-eval                  0.2.2
py-spy                     0.3.14
pyasn1                     0.5.0
pyasn1-modules             0.3.0
Pygments                   2.17.2
PyOpenGL                   3.1.7
pyparsing                  3.1.1
python-dateutil            2.8.2
pytinyrenderer             0.0.14
pytz                       2023.3.post1
PyYAML                     6.0.1
pyzmq                      25.1.0
ray                        1.0.0
redis                      3.4.1
referencing                0.30.2
requests                   2.31.0
requests-oauthlib          1.3.1
rich                       13.7.1
rpds-py                    0.12.0
rsa                        4.9
scipy                      1.10.1
sentry-sdk                 1.34.0
setproctitle               1.3.3
setuptools                 68.0.0
six                        1.16.0
smmap                      5.0.1
soupsieve                  2.5
stack-data                 0.6.2
sympy                      1.12
tensorboard                2.14.0
tensorboard-data-server    0.7.2
tensorboardX               2.6.2.2
tensordict                 0.2.1
tensorstore                0.1.45
termcolor                  2.4.0
tomli                      2.0.1
toolz                      0.12.1
torch                      2.0.1
torchaudio                 2.0.2
torchrl                    0.1.0
torchvision                0.15.2
tornado                    6.1
tqdm                       4.66.1
traitlets                  5.14.0
trimesh                    4.4.1
triton                     2.0.0
typing_extensions          4.8.0
tzdata                     2023.3
urllib3                    2.1.0
wandb                      0.14.2
wcwidth                    0.2.12
Werkzeug                   3.0.1
wheel                      0.41.2
yarl                       1.9.2
zipp                       3.17.0
