### ISSUE TITLE
Ray issue

### ISSUE THREAD

**Issue by tapicl** [Shengjiewang-Jason/EfficientZeroV2#4]
python ez/train.py exp_config=ez/config/exp/atari.yaml
/ez2/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
start 0 train worker...
A.L.E: Arcade Learning Environment (version 0.7.5+db37282)
[Powered by Stella]
env=Atari, game=Asterix, |A|=9, top_m=4, N=16
2024-08-13 09:44:44,452 INFO services.py:1164 -- View the Ray dashboard at http://127.0.0.1:8265/
[main process] Global storage server has been started from main process.
[main process] Batch storage has been initialized.
[main process] Replay buffer server has been started from main process.
[Watchdog Server] Watchdog server initialized.
[main process] Watchdog server has been started from main process.
[Data worker] Start data worker 0 at process 1546446.
[main process] Data workers have all been launched.
2024-08-13 09:44:45,893 WARNING worker.py:1072 -- Failed to unpickle actor class 'DataWorker' for actor ID 88866c7d01000000. Traceback:
Traceback (most recent call last):
  File "/ez2/lib/python3.8/site-packages/ray/function_manager.py", line 493, in _load_actor_class_from_gcs
    actor_class = pickle.loads(pickled_class)
ModuleNotFoundError: No module named 'ez.worker'

**Comment by Shengjiewang-Jason** [comment]
The version of ray is 1.0.0. Do you check it?

**Comment by tapicl** [comment]
Yes: ray 1.0.0

Here is the whole env:

Package                    Version   
-------------------------- ----------
absl-py                    2.1.0     
aiohappyeyeballs           2.3.5     
aiohttp                    3.10.3    
aiohttp-cors               0.7.0     
aioredis                   2.0.1     
aiosignal                  1.3.1     
ale-py                     0.7.5     
antlr4-python3-runtime     4.9.3     
appdirs                    1.4.4     
async-timeout              4.0.3     
attrs                      24.2.0    
AutoROM                    0.4.2     
AutoROM.accept-rom-license 0.6.1     
beautifulsoup4             4.12.3    
blessed                    1.20.0    
cachetools                 5.4.0     
certifi                    2024.7.4  
charset-normalizer         3.3.2     
click                      8.0.4     
cloudpickle                3.0.0     
cmake                      3.30.2    
colorama                   0.4.6     
colorednoise               2.2.0     
colorful                   0.5.6     
Cython                     3.0.11    
Cython-Tree-Module         0.0.0     
distlib                    0.3.8     
dm-control                 1.0.22    
dm-env                     1.6       
dm-tree                    0.1.8     
dmc2gym                    1.0.0     
docker-pycreds             0.4.0     
etils                      1.3.0     
filelock                   3.15.4    
frozenlist                 1.4.1     
gitdb                      4.0.11    
GitPython                  3.1.43    
glfw                       2.7.0     
google                     3.0.0     
google-api-core            2.19.1    
google-auth                2.33.0    
googleapis-common-protos   1.63.2    
gpustat                    1.1.1     
grpcio                     1.43.0    
gym                        0.21.0    
gym-notices                0.0.8     
hydra-core                 1.3.2     
idna                       3.7       
imageio                    2.31.5    
importlib-metadata         8.2.0     
importlib-resources        6.4.0     
jinja2                     3.1.4     
jsonschema                 4.23.0    
jsonschema-specifications  2023.12.1 
kornia                     0.7.3     
kornia-rs                  0.1.5     
labmaze                    1.0.6     
lit                        18.1.8    
lxml                       5.3.0     
MarkupSafe                 2.1.5     
mpmath                     1.3.0     
msgpack                    1.0.8     
mujoco                     3.2.2     
multidict                  6.0.5     
networkx                   3.1       
numpy                      1.21.0    
nvidia-cublas-cu11         11.10.3.66
nvidia-cuda-cupti-cu11     11.7.101  
nvidia-cuda-nvrtc-cu11     11.7.99   
nvidia-cuda-runtime-cu11   11.7.99   
nvidia-cudnn-cu11          8.5.0.96  
nvidia-cufft-cu11          10.9.0.58 
nvidia-curand-cu11         10.2.10.91
nvidia-cusolver-cu11       11.4.0.1  
nvidia-cusparse-cu11       11.7.4.91 
nvidia-ml-py               12.555.43 
nvidia-nccl-cu11           2.14.3    
nvidia-nvtx-cu11           11.7.91   
omegaconf                  2.3.0     
opencensus                 0.11.4    
opencensus-context         0.1.3     
opencv-python              4.10.0.84 
orjson                     3.10.7    
packaging                  24.1      
pathtools                  0.1.2     
pillow                     10.4.0    
pip                        20.0.2    
pkg-resources              0.0.0     
pkgutil-resolve-name       1.3.10    
platformdirs               4.2.2     
prometheus-client          0.20.0    
proto-plus                 1.24.0    
protobuf                   3.20.1    
psutil                     6.0.0     
py-spy                     0.3.14    
pyasn1                     0.6.0     
pyasn1-modules             0.4.0     
PyOpenGL                   3.1.7     
PyOpenGL-accelerate        3.1.7     
pyparsing                  3.1.2     
PyYAML                     6.0.2     
ray                        1.0.0     
redis                      3.4.1     
referencing                0.35.1    
requests                   2.32.3    
rpds-py                    0.20.0    
rsa                        4.9       
scipy                      1.10.1    
sentry-sdk                 2.13.0    
setproctitle               1.3.3     
setuptools                 44.0.0    
six                        1.16.0    
smmap                      5.0.1     
soupsieve                  2.6       
sympy                      1.13.2    
tensordict                 0.2.1     
torch                      2.0.1     
torchaudio                 2.0.2     
torchrl                    0.1.0     
torchvision                0.15.2    
tqdm                       4.66.5    
triton                     2.0.0     
typing-extensions          4.12.2    
UNKNOWN                    0.0.0     
urllib3                    2.2.2     
virtualenv                 20.26.3   
wandb                      0.14.2    
wcwidth                    0.2.13    
wheel                      0.44.0    
yarl                       1.9.4     
zipp                       3.20.0

**Comment by Shengjiewang-Jason** [comment]
Sorry, bro. I am not sure the reason, coz I didn't meet the problem before. But I see some possible reasons, please check [https://github.com/ray-project/ray/issues/5635](https://github.com/ray-project/ray/issues/5635) and [https://stackoverflow.com/questions/71956552/modulenotfounderror-seen-after-the-first-time-a-job-is-run-on-a-ray-cluster](https://stackoverflow.com/questions/71956552/modulenotfounderror-seen-after-the-first-time-a-job-is-run-on-a-ray-cluster).

**Comment by Shengjiewang-Jason** [comment]
Hi, bro. If the problem is solved, can you tag it a solution? If not, you also can send some info here. Thank you.

**Comment by tapicl** [comment]
Thank you for all your help so far. Unfortunately for compatibility I need to work with a more up to date environment.

**Comment by Shengjiewang-Jason** [comment]
ok, I see. You can use conda to manage the python envs.
