### ISSUE TITLE
How much RAM is necessary?

### ISSUE THREAD

**Issue by yifanr** [Shengjiewang-Jason/EfficientZeroV2#6]
`ValueError: After taking into account object store and redis memory usage, the amount of memory on this node available for tasks and actors (-121.85 GB) is less than -241% of total. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).

Getting this error when running the atari script on a system with 48 GB of memory, 16 core cpu. Thank you for your time!

**Comment by Shengjiewang-Jason** [comment]
Oh, I see. you should modify the value of `object_store_memory=150 * 1024 * 1024 * 1024 if config.env.image_based else 100 * 1024 * 1024 * 1024)`.  It is large now, but you can reduce it to 20G.

**Comment by yifanr** [comment]
Thanks! Out of curiosity, is 20G the minimum?
